name: Build Extension

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm install
            
            - name: Gulp Build
              run: gulp build
            
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                name: extension-build
                path: dist/**/*.zip